### ISSUE TITLE
Mastodon: can't enter a query

### ISSUE THREAD

**Issue by defulmere** [Ptujec/LaunchBar#17]
When I invoke the Mastodon Search action (latest version as of today) I'm taken directly to my instance instead of being prompted to enter a search query.

Sending text to the action works fine: 

1. Invoke Launchbar.
2. Filter to get Enter Text action.
3. Type a query.
4. Hit tab and send the text to Mastodon Search.
6. Search results are presented.

Using the action directly does not:

1. Invoke Launchbar.
2. Filter to get Mastodon Search action.
3. Press Enter.
4. At this point I'm taken directly to my instance instead of being presented with an input.

**Comment by Ptujec** [comment]
That was actually intentional. Text entry is usually triggered by `space`. That way I can use the same action to just open Mastodon in Safari (with `enter`) or search (with `space`). 
If you are not used to that it is easy to change the behavior by setting `LBRequiresArgument` to `true` either in Action Editor (`⇧⌘E`) by clicking the checkbox or if you edit the info plist and add:

```
<key>LBRequiresArgument</key>
<true/>
```		
			
Note: If you edit actions in the Action Editor the integration with [Action Updates](https://renaghan.com/launchbar/action-updates/) by @prenagha will stop working. (Obdev promised to fix that in the next update).
